// ============================================================
// SEED DATA – Initialwerte bis Backend-API verbunden ist
// Wird NUR als Fallback genutzt wenn API_BASE nicht gesetzt.
// ============================================================

import { Lead, MandateTracking, OperationsCustomer } from './types';

export const SEED_LEADS: Lead[] = [
  {
    lead_id: 'LEAD-001',
    company_name: 'Haustechnik Müller GmbH',
    branche: 'technische_wartung',
    umsatz: 8500000,
    ebit_marge: 0.11,
    mitarbeiteranzahl: 52,
    controller_anzahl: 1,
    ansprechpartner: 'Thomas Müller',
    telefon: '+49 89 1234567',
    emails: ['mueller@haustechnik-mueller.de'],
    adresse: 'Industriestr. 12, 80939 München',
    pipeline_status: 'angebot',
    next_action: 'Follow-up Call nach Angebot',
    next_action_date: '2026-04-18',
    icp_score: 95,
    lead_source: 'empfehlung',
    created_at: '2026-03-01T10:00:00Z',
    updated_at: '2026-04-10T14:30:00Z',
    created_by: 'gregory@meyerdecision.com',
    is_archived: false,
    archived_at: null,
    duplicate_flag: false,
    duplicate_reference_id: null,
    last_modified_at: '2026-04-10T14:30:00Z',
  },
  {
    lead_id: 'LEAD-002',
    company_name: 'TechServ Solutions AG',
    branche: 'industrienahe_service',
    umsatz: 14200000,
    ebit_marge: 0.09,
    mitarbeiteranzahl: 68,
    controller_anzahl: 2,
    ansprechpartner: 'Sandra Weber',
    telefon: '+49 711 9876543',
    emails: ['weber@techserv-solutions.de'],
    adresse: 'Werksweg 44, 70563 Stuttgart',
    pipeline_status: 'qualifiziert',
    next_action: 'Discovery Call vereinbaren',
    next_action_date: '2026-04-15',
    icp_score: 100,
    lead_source: 'linkedin',
    created_at: '2026-02-15T09:00:00Z',
    updated_at: '2026-04-08T11:00:00Z',
    created_by: 'gregory@meyerdecision.com',
    is_archived: false,
    archived_at: null,
    duplicate_flag: false,
    duplicate_reference_id: null,
    last_modified_at: '2026-04-08T11:00:00Z',
  },
  {
    lead_id: 'LEAD-003',
    company_name: 'Facility Pro GmbH',
    branche: 'b2b_contracting',
    umsatz: 5800000,
    ebit_marge: 0.14,
    mitarbeiteranzahl: 35,
    controller_anzahl: 0,
    ansprechpartner: 'Michael Braun',
    telefon: '+49 221 5551234',
    emails: ['braun@facilitypro.de'],
    adresse: 'Am Rheinufer 8, 50668 Köln',
    pipeline_status: 'gewonnen',
    next_action: 'Vertrag vorbereiten',
    next_action_date: '2026-04-12',
    icp_score: 90,
    lead_source: 'cold_call',
    created_at: '2026-01-20T08:00:00Z',
    updated_at: '2026-04-05T16:00:00Z',
    created_by: 'nhi@meyerdecision.com',
    is_archived: false,
    archived_at: null,
    duplicate_flag: false,
    duplicate_reference_id: null,
    last_modified_at: '2026-04-05T16:00:00Z',
  },
  {
    lead_id: 'LEAD-004',
    company_name: 'Wartung Plus KG',
    branche: 'technische_wartung',
    umsatz: 3200000,
    ebit_marge: 0.07,
    mitarbeiteranzahl: 22,
    controller_anzahl: 0,
    ansprechpartner: 'Petra Schneider',
    telefon: '+49 40 6667788',
    emails: ['schneider@wartungplus.de'],
    adresse: 'Hafenstr. 17, 20459 Hamburg',
    pipeline_status: 'kontaktiert',
    next_action: 'Unterlagen zusenden',
    next_action_date: '2026-04-20',
    icp_score: 52,
    lead_source: 'website',
    created_at: '2026-03-10T14:00:00Z',
    updated_at: '2026-04-09T10:00:00Z',
    created_by: 'gregory@meyerdecision.com',
    is_archived: false,
    archived_at: null,
    duplicate_flag: false,
    duplicate_reference_id: null,
    last_modified_at: '2026-04-09T10:00:00Z',
  },
  {
    lead_id: 'LEAD-005',
    company_name: 'Industrieservice Becker & Co.',
    branche: 'industrienahe_service',
    umsatz: 19500000,
    ebit_marge: 0.16,
    mitarbeiteranzahl: 78,
    controller_anzahl: 1,
    ansprechpartner: 'Klaus Becker',
    telefon: '+49 30 4445566',
    emails: ['becker@is-becker.de'],
    adresse: 'Fabrikstr. 91, 12435 Berlin',
    pipeline_status: 'verhandlung',
    next_action: 'Vertragsbedingungen finalisieren',
    next_action_date: '2026-04-14',
    icp_score: 85,
    lead_source: 'empfehlung',
    created_at: '2026-02-01T11:00:00Z',
    updated_at: '2026-04-11T09:30:00Z',
    created_by: 'nhi@meyerdecision.com',
    is_archived: false,
    archived_at: null,
    duplicate_flag: false,
    duplicate_reference_id: null,
    last_modified_at: '2026-04-11T09:30:00Z',
  },
  {
    lead_id: 'LEAD-006',
    company_name: 'Gebäudetechnik Hoffmann',
    branche: 'technische_wartung',
    umsatz: 6100000,
    ebit_marge: 0.10,
    mitarbeiteranzahl: 40,
    controller_anzahl: 1,
    ansprechpartner: 'Jens Hoffmann',
    telefon: '+49 69 1112233',
    emails: ['hoffmann@gt-hoffmann.de'],
    adresse: 'Mainzer Landstr. 200, 60326 Frankfurt',
    pipeline_status: 'neu',
    next_action: 'Erstansprache vorbereiten',
    next_action_date: '2026-04-22',
    icp_score: 75,
    lead_source: 'linkedin',
    created_at: '2026-04-08T10:00:00Z',
    updated_at: '2026-04-08T10:00:00Z',
    created_by: 'gregory@meyerdecision.com',
    is_archived: false,
    archived_at: null,
    duplicate_flag: false,
    duplicate_reference_id: null,
    last_modified_at: '2026-04-08T10:00:00Z',
  },
  {
    lead_id: 'LEAD-007',
    company_name: 'ClearServ Outsourcing GmbH',
    branche: 'b2b_contracting',
    umsatz: 11800000,
    ebit_marge: 0.12,
    mitarbeiteranzahl: 55,
    controller_anzahl: 2,
    ansprechpartner: 'Anke Fischer',
    telefon: '+49 211 7778899',
    emails: ['fischer@clearserv.de'],
    adresse: 'Königsallee 56, 40212 Düsseldorf',
    pipeline_status: 'angebot',
    next_action: 'Angebot nachfassen',
    next_action_date: '2026-04-16',
    icp_score: 88,
    lead_source: 'email',
    created_at: '2026-03-05T15:00:00Z',
    updated_at: '2026-04-10T08:00:00Z',
    created_by: 'nhi@meyerdecision.com',
    is_archived: false,
    archived_at: null,
    duplicate_flag: false,
    duplicate_reference_id: null,
    last_modified_at: '2026-04-10T08:00:00Z',
  },
  {
    lead_id: 'LEAD-008',
    company_name: 'Mega Bau Service AG',
    branche: '',
    umsatz: 45000000,
    ebit_marge: 0.05,
    mitarbeiteranzahl: 350,
    controller_anzahl: 8,
    ansprechpartner: 'Frank Groß',
    telefon: '+49 89 9990000',
    emails: ['gross@megabau.de'],
    adresse: 'Leopoldstr. 1, 80802 München',
    pipeline_status: 'verloren',
    next_action: '',
    next_action_date: null,
    icp_score: 10,
    lead_source: 'cold_call',
    created_at: '2026-01-10T09:00:00Z',
    updated_at: '2026-02-20T14:00:00Z',
    created_by: 'gregory@meyerdecision.com',
    is_archived: true,
    archived_at: '2026-02-20T14:00:00Z',
    duplicate_flag: false,
    duplicate_reference_id: null,
    last_modified_at: '2026-02-20T14:00:00Z',
  },
];

// Simplified: 1 customer = 1 contract (no multi-contract fields)
export const SEED_MANDATES: MandateTracking[] = [
  {
    customer_id: 'CUST-001',
    company_name: 'MUSTERMANN TECHNIK GmbH',
    ansprechpartner: 'Hans Mustermann',
    emails: ['mustermann@mustermann-technik.de'],
    vertragsbeginn: '2025-07-01',
    vertragsende: null,
    vertragsart: 'dienstleistungsvertrag',
    gebuchte_dienstleistung: 'Advisory',
    monatliches_honorar: 4500,
    setup_fee: 3000,
    mandate_status: 'active',
    notes: 'Referenzkunde, sehr zufrieden',
    last_auto_sync: '2026-04-12T07:00:00Z',
    manually_edited: false,
  },
  {
    customer_id: 'CUST-002',
    company_name: 'BETRIEB ALPHA GmbH',
    ansprechpartner: 'Maria Schulz',
    emails: ['schulz@betrieb-alpha.de'],
    vertragsbeginn: '2025-09-01',
    vertragsende: '2026-08-31',
    vertragsart: 'rahmenvertrag',
    gebuchte_dienstleistung: 'Advisory',
    monatliches_honorar: 3800,
    setup_fee: 2500,
    mandate_status: 'active',
    notes: '',
    last_auto_sync: '2026-04-12T07:00:00Z',
    manually_edited: false,
  },
  {
    customer_id: 'CUST-003',
    company_name: 'HANDWERK BETA KG',
    ansprechpartner: 'Peter Lang',
    emails: ['lang@handwerk-beta.de'],
    vertragsbeginn: '2025-11-01',
    vertragsende: null,
    vertragsart: 'dienstleistungsvertrag',
    gebuchte_dienstleistung: 'Advisory',
    monatliches_honorar: 2800,
    setup_fee: 2000,
    mandate_status: 'active',
    notes: '',
    last_auto_sync: '2026-04-12T07:00:00Z',
    manually_edited: true,
  },
  {
    customer_id: 'CUST-004',
    company_name: 'INDUSTRIE GAMMA GmbH',
    ansprechpartner: 'Karla Winter',
    emails: ['winter@industrie-gamma.de'],
    vertragsbeginn: '2026-01-01',
    vertragsende: '2026-12-31',
    vertragsart: 'rahmenvertrag',
    gebuchte_dienstleistung: 'Advisory',
    monatliches_honorar: 3200,
    setup_fee: 2500,
    mandate_status: 'active',
    notes: 'Liquiditätsrisiko beobachten',
    last_auto_sync: '2026-04-12T07:00:00Z',
    manually_edited: false,
  },
  {
    customer_id: 'CUST-005',
    company_name: 'Facility Pro GmbH',
    ansprechpartner: 'Michael Braun',
    emails: ['braun@facilitypro.de'],
    vertragsbeginn: null,
    vertragsende: null,
    vertragsart: '',
    gebuchte_dienstleistung: '',
    monatliches_honorar: null,
    setup_fee: null,
    mandate_status: 'onboarding',
    notes: 'Gerade gewonnen, Vertrag wird vorbereitet',
    last_auto_sync: '2026-04-12T07:00:00Z',
    manually_edited: false,
  },
];

export const SEED_OPERATIONS: OperationsCustomer[] = [
  {
    customer_id: 'CUST-001',
    company_name: 'MUSTERMANN TECHNIK GmbH',
    ansprechpartner: 'Hans Mustermann',
    emails: ['mustermann@mustermann-technik.de'],
    monatliches_honorar: 4500,
    mandate_status: 'active',
    angebot_sent: true,
    vertrag_sent: true,
    unterlagen_sent: true,
    monthly_data: {
      '2026-04': { daten_erhalten: true, daten_valide: true, call_durchgefuehrt: true, reminder_sent: false, rechnung_sent: true, upload_status: 'uploaded', file_count: 12, last_upload_date: '2026-04-08T14:30:00Z' },
      '2026-03': { daten_erhalten: true, daten_valide: true, call_durchgefuehrt: true, reminder_sent: false, rechnung_sent: true, upload_status: 'uploaded', file_count: 10, last_upload_date: '2026-03-07T10:00:00Z' },
      '2026-02': { daten_erhalten: true, daten_valide: true, call_durchgefuehrt: true, reminder_sent: false, rechnung_sent: true, upload_status: 'uploaded', file_count: 9, last_upload_date: '2026-02-06T09:00:00Z' },
    },
    // Legacy flat fields (derived from current month for backward compat)
    daten_erhalten: true, daten_valide: true, call_durchgefuehrt: true, ampel_status: 'GRUEN',
    upload_status: 'uploaded', file_count: 12, last_upload_date: '2026-04-08T14:30:00Z',
    reminder_sent: false, rechnung_sent: true,
  },
  {
    customer_id: 'CUST-002',
    company_name: 'BETRIEB ALPHA GmbH',
    ansprechpartner: 'Maria Schulz',
    emails: ['schulz@betrieb-alpha.de'],
    monatliches_honorar: 3800,
    mandate_status: 'active',
    angebot_sent: true,
    vertrag_sent: true,
    unterlagen_sent: true,
    monthly_data: {
      '2026-04': { daten_erhalten: true, daten_valide: true, call_durchgefuehrt: false, reminder_sent: false, rechnung_sent: false, upload_status: 'uploaded', file_count: 8, last_upload_date: '2026-04-06T09:15:00Z' },
      '2026-03': { daten_erhalten: true, daten_valide: true, call_durchgefuehrt: true, reminder_sent: false, rechnung_sent: true, upload_status: 'uploaded', file_count: 7, last_upload_date: '2026-03-05T08:00:00Z' },
      '2026-02': { daten_erhalten: true, daten_valide: true, call_durchgefuehrt: true, reminder_sent: false, rechnung_sent: true, upload_status: 'uploaded', file_count: 8, last_upload_date: '2026-02-04T11:00:00Z' },
    },
    daten_erhalten: true, daten_valide: true, call_durchgefuehrt: false, ampel_status: 'GELB',
    upload_status: 'uploaded', file_count: 8, last_upload_date: '2026-04-06T09:15:00Z',
    reminder_sent: false, rechnung_sent: false,
  },
  {
    customer_id: 'CUST-003',
    company_name: 'HANDWERK BETA KG',
    ansprechpartner: 'Peter Lang',
    emails: ['lang@handwerk-beta.de'],
    monatliches_honorar: 2800,
    mandate_status: 'active',
    angebot_sent: true,
    vertrag_sent: true,
    unterlagen_sent: true,
    monthly_data: {
      '2026-04': { daten_erhalten: true, daten_valide: false, call_durchgefuehrt: false, reminder_sent: false, rechnung_sent: true, upload_status: 'uploaded', file_count: 5, last_upload_date: '2026-04-09T11:00:00Z' },
      '2026-03': { daten_erhalten: true, daten_valide: true, call_durchgefuehrt: true, reminder_sent: false, rechnung_sent: true, upload_status: 'uploaded', file_count: 6, last_upload_date: '2026-03-08T14:00:00Z' },
      '2026-02': { daten_erhalten: false, daten_valide: false, call_durchgefuehrt: false, reminder_sent: true, rechnung_sent: false, upload_status: 'pending', file_count: 0, last_upload_date: null },
    },
    daten_erhalten: true, daten_valide: false, call_durchgefuehrt: false, ampel_status: 'GELB',
    upload_status: 'uploaded', file_count: 5, last_upload_date: '2026-04-09T11:00:00Z',
    reminder_sent: false, rechnung_sent: true,
  },
  {
    customer_id: 'CUST-004',
    company_name: 'INDUSTRIE GAMMA GmbH',
    ansprechpartner: 'Karla Winter',
    emails: ['winter@industrie-gamma.de'],
    monatliches_honorar: 3200,
    mandate_status: 'active',
    angebot_sent: true,
    vertrag_sent: true,
    unterlagen_sent: false,
    monthly_data: {
      '2026-04': { daten_erhalten: false, daten_valide: false, call_durchgefuehrt: false, reminder_sent: true, rechnung_sent: false, upload_status: 'pending', file_count: 0, last_upload_date: null, is_overdue: true },
      '2026-03': { daten_erhalten: true, daten_valide: true, call_durchgefuehrt: false, reminder_sent: true, rechnung_sent: false, upload_status: 'uploaded', file_count: 4, last_upload_date: '2026-03-12T16:00:00Z' },
    },
    daten_erhalten: false, daten_valide: false, call_durchgefuehrt: false, ampel_status: 'ROT',
    upload_status: 'pending', file_count: 0, last_upload_date: null,
    reminder_sent: true, rechnung_sent: false,
  },
  {
    customer_id: 'CUST-005',
    company_name: 'Facility Pro GmbH',
    ansprechpartner: 'Michael Braun',
    emails: ['braun@facilitypro.de'],
    monatliches_honorar: 0,
    mandate_status: 'onboarding',
    angebot_sent: true,
    vertrag_sent: false,
    unterlagen_sent: false,
    monthly_data: {},
    daten_erhalten: false, daten_valide: false, call_durchgefuehrt: false, ampel_status: 'ROT',
    upload_status: 'pending', file_count: 0, last_upload_date: null,
    reminder_sent: false, rechnung_sent: false,
  },
];
